name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Setup env
        run: |
          echo "PORT=5001" >> .env
          echo "MONGO_URI=mongodb://localhost:27017/test" >> .env
          echo "REDIS_HOST=localhost" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "API_KEY=test_api_key" >> .env
          echo "FRONTEND_URL=http://localhost:3000" >> .env

      - name: Run tests
        run: npm test
